### ISSUE TITLE
400 errors cause crash

### ISSUE THREAD

**Issue by tonybroadbent** [rgstephens/node-red-contrib-graphql#51]
If the gql request fails with a code 400, nothing appears in the node-red debug log. Syslog contains something like:
Node-RED[372]: 17 Aug 12:39:22 - [info] [graphql:Get Octopus] undefined
Node-RED[372]: (node:372) UnhandledPromiseRejectionWarning: TypeError: **Cannot set property 'graphql' of undefined**
Node-RED[372]:     at /home/pi/.node-red/node_modules/node-red-contrib-graphql/graphql.js:192:36
Node-RED[372]:     at runMicrotasks (<anonymous>)
Node-RED[372]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Modifying line 192 in graph.js as below, and details of the problem are visible in the debugging output.
BEFORE:  node.msg.payload.graphql = { error };
AFTER:     node.msg = { payload: error };

**Comment by tonybroadbent** [comment]
Yes, I think the "fix" for issue 32 has broken a few things around error handling.  However, I've managed to learn gql and thereby fix my car charging problem, so many thanks for producing this great piece of code.

**Comment by rgstephens** [comment]
Thanks for reporting and troubleshooting this.

**Comment by tonybroadbent** [comment]
Hi, I've completely reinstalled my RPI so clean install and I'm hitting this problem again.
```
2024-06-12T00:59:47.207241+01:00 raspberrypi Node-RED[1150870]: 12 Jun 00:59:47 - [error] TypeError: Cannot set properties of undefined (setting 'graphql')
2024-06-12T00:59:47.207401+01:00 raspberrypi Node-RED[1150870]:     at /home/pi/.node-red/node_modules/node-red-contrib-graphql/graphql.js:192:36
2024-06-12T00:59:47.207519+01:00 raspberrypi Node-RED[1150870]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-12T00:59:47.240438+01:00 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
```
Error causes the whole of node-red to restart.
My fix in callGraphQLServer was to initialise the payload:
` node.msg.payload = {};`
So the  line below doesn't cause a crash if node.msg has no payload:
`node.msg.payload.graphql = { error };`
Cheers,
Tony
